import dataclasses
import enum


class OrderHistoryActionEnum(enum.IntEnum):
    ORDER_VIEWED = 0
    ORDER_SAVED = 1
    ATTACHMENT_ADDED = 2
    ORDER_DONE = 3
    ORDER_DONE_REVOKED = 4
    ORDER_REWRITTEN = 5
    ORDER_CREATED_BY_REWRITE = 6
    ORDER_CREATED = 7
    ORDER_CREATED_BY_COPY = 8
    ORDER_CANCELATION_REVOKED = 9
    ORDER_CANCELED = 10
    ATTACHMENTS_DOWNLOADED = 11
    FOLLOWUP_SET = 12
    RESPONSIBLE_EMPLOYEE_SET = 13
    AREA_ASSIGNED = 14
    ORDER_TYPE_SET = 15
    ORDER_TYPE_CHANGED = 16
    TOUR_MAIL_SENT = 17
    TOUR_MAIL_REVOKED = 18

