# Generated by Django 3.2.7 on 2021-10-17 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuftragBild',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('upload_datetime', models.DateTimeField(auto_now=True)),
                ('bild_pfad', models.ImageField(upload_to='clex_images')),
            ],
            options={
                'db_table': 'auftrag_bilder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClexImageUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(max_length=255)),
                ('expert_employee_id', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
