# Generated by Django 3.2.7 on 2021-10-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleximages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleximageuser',
            name='login_name',
        ),
        migrations.RemoveField(
            model_name='cleximageuser',
            name='expert_employee_id',
        ),
    ]
