# Generated by Django 3.2.2 on 2021-05-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTemplate',
            fields=[
                ('firma', models.IntegerField(primary_key=True, serialize=False)),
                ('confirmation', models.TextField(default='Bestätigung')),
                ('reminder', models.TextField(default='Erinnerung')),
            ],
        ),
    ]
