# Generated by Django 3.2.2 on 2021-05-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_customertemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmails',
            fields=[
                ('auftrag_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sent_confirmation_datetime', models.DateTimeField()),
                ('sent_reminder_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Reminder sent datetime')),
            ],
        ),
        migrations.CreateModel(
            name='SentEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_interval_hours', models.IntegerField()),
            ],
        ),
    ]
