# Generated by Django 3.2.2 on 2021-05-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_sentemails_sentemailsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemailsettings',
            name='logfile_dir',
            field=models.CharField(default='C:\\logs', max_length=255),
        ),
    ]
