# Generated by Django 3.2.2 on 2021-05-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_sentemailsettings_logfile_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemailsettings',
            name='smtp_password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sentemailsettings',
            name='smtp_server',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sentemailsettings',
            name='smtp_user',
            field=models.CharField(default='', max_length=255),
        ),
    ]
