# Generated by Django 3.2.2 on 2021-05-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_auto_20210508_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemailsettings',
            name='smtp_port',
            field=models.CharField(default='', max_length=8),
        ),
    ]
