# Generated by Django 3.2.2 on 2021-05-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_sentemailsettings_smtp_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='sentemailsettings',
            name='use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sentemailsettings',
            name='use_tls',
            field=models.BooleanField(default=False),
        ),
    ]
