# Generated by Django 3.2.2 on 2021-05-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_auto_20210509_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemailsettings',
            name='newsletter_link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sentemailsettings',
            name='newsletter_link_text',
            field=models.CharField(default='', max_length=255),
        ),
    ]
