# Generated by Django 3.2.2 on 2021-05-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_auto_20210509_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemailsettings',
            name='post_text_format',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sentemailsettings',
            name='pre_text_format',
            field=models.TextField(default=''),
        ),
    ]
