# Generated by Django 3.2.2 on 2021-05-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_auto_20210513_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemailsettings',
            name='calendar_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sentemailsettings',
            name='calendar_subject',
            field=models.CharField(default='Ihr Termin', max_length=255),
        ),
    ]
