# Generated by Django 3.2.2 on 2021-05-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_auto_20210513_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemailsettings',
            name='cc_target',
            field=models.EmailField(default='', help_text='If set, always adds this address to CC', max_length=255),
        ),
        migrations.AddField(
            model_name='sentemailsettings',
            name='test_mailing',
            field=models.BooleanField(default=False, help_text='If enabled, only sends the e-mail to CC'),
        ),
    ]
