# Generated by Django 3.2.2 on 2021-05-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_auto_20210519_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemailsettings',
            name='calendar_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sentemailsettings',
            name='cc_target',
            field=models.EmailField(blank=True, default='', help_text='If set, adds this address to CC', max_length=255),
        ),
        migrations.AlterField(
            model_name='sentemailsettings',
            name='newsletter_link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sentemailsettings',
            name='newsletter_link_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sentemailsettings',
            name='remind_interval_hours',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='sentemailsettings',
            name='test_mailing',
            field=models.BooleanField(default=False, help_text='If enabled, removes the mail recipient'),
        ),
    ]
