# Generated by Django 3.2.2 on 2021-06-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0012_auto_20210524_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemailsettings',
            name='calendar_description',
            field=models.TextField(blank=True, default='', help_text='.ics file description'),
        ),
        migrations.AlterField(
            model_name='sentemailsettings',
            name='calendar_subject',
            field=models.CharField(default='Ihr Termin', help_text='.ics file subject', max_length=255),
        ),
        migrations.AlterField(
            model_name='sentemailsettings',
            name='newsletter_link',
            field=models.CharField(blank=True, default='', help_text='Not in use yet', max_length=255),
        ),
        migrations.AlterField(
            model_name='sentemailsettings',
            name='newsletter_link_text',
            field=models.CharField(blank=True, default='', help_text='Not in use yet', max_length=255),
        ),
        migrations.AlterField(
            model_name='sentemailsettings',
            name='post_text_format',
            field=models.TextField(default='', help_text='HTML content injected after client-specific template'),
        ),
        migrations.AlterField(
            model_name='sentemailsettings',
            name='pre_text_format',
            field=models.TextField(default='', help_text='HTML content injected before client-specific template'),
        ),
        migrations.AlterField(
            model_name='sentemailsettings',
            name='remind_interval_hours',
            field=models.IntegerField(default=24, help_text='Duration in hours before a reminder is sent'),
        ),
        migrations.AlterField(
            model_name='sentemailsettings',
            name='test_mailing',
            field=models.BooleanField(default=True, help_text='If enabled, removes the mail recipient and only sends to CC'),
        ),
    ]
