# Generated by Django 3.2.2 on 2021-06-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_auto_20210625_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentemailsettings',
            name='post_text_format',
        ),
        migrations.RemoveField(
            model_name='sentemailsettings',
            name='pre_text_format',
        ),
        migrations.AddField(
            model_name='customertemplate',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sentemailsettings',
            name='mail_template',
            field=models.TextField(default='', help_text="HTML mail content. Possible placeholders:\n        - %appointment_data% (includes the customer's date, time, ...)\n        - %content% (dynamic content included at the bottom of the mail)\n    "),
        ),
    ]
