# Generated by Django 3.2.2 on 2021-06-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0014_auto_20210625_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemailsettings',
            name='default_confirmation',
            field=models.TextField(default='Bestätigung'),
        ),
        migrations.AddField(
            model_name='sentemailsettings',
            name='default_reminder',
            field=models.TextField(default='Erinnerung'),
        ),
        migrations.AlterField(
            model_name='customertemplate',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sentemailsettings',
            name='mail_template',
            field=models.TextField(blank=True, help_text="HTML mail content. Possible placeholders:\n        - %appointment_data% (includes the customer's date, time, ...)\n        - %content% (dynamic content included at the bottom of the mail)\n    "),
        ),
    ]
