# Generated by Django 3.2.2 on 2021-06-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0015_auto_20210625_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemailsettings',
            name='smtp_sender',
            field=models.CharField(default='auftrag@claimsexperts.de', help_text='Sender mail address', max_length=255),
        ),
    ]
