# Generated by Django 3.2.2 on 2021-06-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0016_sentemailsettings_smtp_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('guid', models.CharField(blank=True, max_length=64, null=True)),
                ('anlagedatum', models.DateTimeField()),
                ('firma', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('name2', models.CharField(blank=True, max_length=256, null=True)),
                ('strasse_haus_nr', models.CharField(blank=True, max_length=256, null=True)),
                ('plz', models.CharField(blank=True, max_length=5, null=True)),
                ('ort', models.CharField(blank=True, max_length=256, null=True)),
                ('telefon', models.CharField(blank=True, max_length=64, null=True)),
                ('handy', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('internet', models.CharField(blank=True, max_length=256, null=True)),
                ('platz', models.CharField(blank=True, max_length=256, null=True)),
                ('reihe', models.CharField(blank=True, max_length=256, null=True)),
                ('stellplatz', models.CharField(blank=True, max_length=256, null=True)),
                ('rolle', models.IntegerField(blank=True, null=True)),
                ('auftrag_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'adresse',
                'managed': False,
            },
        ),
    ]
