# Generated by Django 3.2.2 on 2021-07-25 17:29

from django.db import migrations, models
from scheduling.management.util import set_auftragsart_blacklist, reverse_auftragsart_blacklist


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0017_adresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuftragsartBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auftragsart', models.CharField(max_length=255, unique=True)),
                ('blacklisted', models.BooleanField(default=True, help_text='If set, Auftragsart will be skipped for mail delivery')),
            ],
        ),
        migrations.RunPython(set_auftragsart_blacklist, reverse_auftragsart_blacklist),
        migrations.AddField(
            model_name='sentemails',
            name='auftrag_date',
            field=models.DateTimeField(blank=True, help_text='Used to check if Auftrag date was changed', null=True),
        ),
        migrations.AddField(
            model_name='sentemailsettings',
            name='mail_error_receiver',
            field=models.CharField(max_length=255, blank=True, default='schaden@claimsexperts.de', help_text='Default receiving e-mail in case reminder/confirmation cannot be sent'),
        ),
        migrations.AddField(
            model_name='sentemailsettings',
            name='mail_errors',
            field=models.BooleanField(default=False, help_text='If enabled, sends failed mail deliveries to respective Mitarbeiter, or to mail error receiver if Mitarbeiter is not set'),
        ),
    ]
