# Generated by Django 2.2.13 on 2020-06-05 15:09

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='HairColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField()),
                ('published', models.TimeField(auto_now=True)),
                ('description', models.TextField()),
                ('plan', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('resolution_date', models.TimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('location', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'users',
                'abstract': False,
                'verbose_name': 'user',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Puppet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('serial', models.CharField(max_length=64)),
                ('connector', models.CharField(max_length=64)),
                ('shirt_name', models.CharField(max_length=64)),
                ('picture', models.BinaryField()),
                ('hair_color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hair_color', to='api.HairColor')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.User')),
                ('pants_color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pants_color', to='api.Color')),
                ('shirt_color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shirt_color', to='api.Color')),
            ],
        ),
        migrations.CreateModel(
            name='IssueData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=64)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Issue')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='handler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.User'),
        ),
        migrations.AddField(
            model_name='issue',
            name='puppet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Puppet'),
        ),
    ]
