# Generated by Django 2.2.13 on 2020-06-05 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200605_1518'),
    ]

    operations = [
    ]
