# Generated by Django 2.2.13 on 2020-06-05 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200605_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='handler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.User'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='puppet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='issues', to='api.Puppet'),
        ),
        migrations.AlterField(
            model_name='issuedata',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='api.Issue'),
        ),
    ]
