# Generated by Django 2.2.13 on 2020-06-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200605_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedata',
            name='data',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
