# Generated by Django 2.2.13 on 2020-06-05 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200605_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuedata',
            old_name='data',
            new_name='ref',
        ),
    ]
