# Generated by Django 2.2.13 on 2020-06-07 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200605_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppet',
            name='shoe_color',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shoe_color', to='api.Color'),
            preserve_default=False,
        ),
    ]
