# Generated by Django 2.2.13 on 2020-06-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_puppet_shoe_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puppet',
            name='shoe_color',
        ),
    ]
