# Generated by Django 2.2.13 on 2020-06-07 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_puppet_shoe_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppet',
            name='shoe_color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shoe_color', to='api.Color'),
            preserve_default=False,
        ),
    ]
