# Generated by Django 2.2.13 on 2020-06-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_puppet_shoe_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppet',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
