# Generated by Django 2.2.13 on 2020-06-09 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_editlock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editlock',
            name='user',
        ),
    ]
