# Generated by Django 2.2.13 on 2020-06-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_editlock_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='puppet',
            name='last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
