# Generated by Django 2.2.13 on 2020-06-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200609_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='last_edit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
