# Generated by Django 3.0.7 on 2020-06-24 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_delete_editlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='creator',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.DO_NOTHING, related_name='issuecreator', to='api.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='handler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='issuehandler', to='api.User'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='resolution_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='puppet',
            name='picture',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
