# Generated by Django 4.1.7 on 2023-03-23 12:21

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MdlQuestion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("parent", models.BigIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("questiontext", models.TextField()),
                ("questiontextformat", models.IntegerField()),
                ("generalfeedback", models.TextField()),
                ("generalfeedbackformat", models.IntegerField()),
                ("defaultmark", models.DecimalField(decimal_places=7, max_digits=12)),
                ("penalty", models.DecimalField(decimal_places=7, max_digits=12)),
                ("qtype", models.CharField(max_length=20)),
                ("length", models.BigIntegerField()),
                ("stamp", models.CharField(max_length=255)),
                ("timecreated", models.BigIntegerField()),
                ("timemodified", models.BigIntegerField()),
                ("createdby", models.BigIntegerField(blank=True, null=True)),
                ("modifiedby", models.BigIntegerField(blank=True, null=True)),
            ],
            options={"db_table": "mdl_question", "managed": False,},
        ),
        migrations.CreateModel(
            name="MdlQuestionAnswers",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("answer", models.TextField()),
                ("answerformat", models.IntegerField()),
                ("fraction", models.DecimalField(decimal_places=7, max_digits=12)),
                ("feedback", models.TextField()),
                ("feedbackformat", models.IntegerField()),
            ],
            options={"db_table": "mdl_question_answers", "managed": False,},
        ),
    ]
